### Send POST request with json body
POST http://localhost:8080/staff/create
Content-Type: application/json

{
  "staffName": "Ilya",
  "stafflastName": "Ivanov",
  "dateOfReg" : "05.03.2022",
  "typeOfStaff" : "Повар"
}


###GET
GET http://localhost:8080/staff


### Send DELETE request with json body
DELETE http://localhost:8080/staff/delete/2
