app:
  api:
    users:
      confirmAddress: ${CONFIRM_ADDR:http://localhost:3017/}
server:
  port: ${PORT:8087}
  public-port: ${PUBLIC_PORT:${server.port}}
  public-host: ${PUBLIC_HOST:localhost}
management:
  server:
    port: ${server.public-port}
spring:
  application:
    name: ${eureka.instance.appname}
  main:
    banner-mode: off
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  security:
    user:
      password: ${eureka.password}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USER:test}
    password: ${MAIL_PASS:test}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
eureka:
  instance:
    appname: USER
    nonSecurePort: ${server.public-port}
    statusPageUrl: https://${eureka.instance.hostname}:${server.public-port}/actuator/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.public-port}/actuator/health
    homePageUrl: https://${eureka.instance.hostname}:${server.public-port}/
  password: ${USER_PASSWORD:password}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/eureka/}
---
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://test:test@database:5432/test}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASS:}
  config:
    activate:
      on-profile: prod
  h2:
    console.enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
